[[ISSUERS]]
address = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
name = "CONTINENTAL WICK"
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
url = "https://wicktoken.net"

[[TOKENS]]
issuer = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
currency = "WCK"
name = "$WCK"
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
icon = "https://wicktoken.net/assets/wck-logo.png"

[[TOKENS.URLS]]
url = "https://wicktoken.net"
type = "website"

[[TOKENS.URLS]]
url = "https://x.com/wicktoken"
type = "social"
