[[ISSUERS]]
address = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
name = "CONTINENTAL WICK"

[[TOKENS]]
issuer = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
currency = "$WCK"
name = "CONTINENTAL WICK"
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
icon = "ipfs://bafkreiajbbmrlqvhxajx7tihkbgnlwsolovkxxjjks4r7drs3w75oze3xy"

[[TOKENS.URLS]]
url = "https://wicktoken.net"
type = "website"

[[TOKENS.URLS]]
url = "https://x.com/wick_token"
type = "social"
