# XRPL Token TOML for $WCK
# Last updated: 2025-08-12

[[CURRENCIES]]
code          = "WCK"
currency_hex  = "57434B0000000000000000000000000000000000"
issuer        = "rpFVEydkZrUjf4tcbLeDeVqXm5zYQGtXWm"
network       = "main"
name          = "WCK"
desc          = "The official $WCK token — native to the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution. The Utility That Memes. Total supply 100,000,000."
icon          = "https://wicktoken.net/logo.png"
display_decimals = 6

[[CURRENCIES.urls]]
type  = "website"
title = "Official Website"
url   = "https://wicktoken.net"

[[CURRENCIES.urls]]
type  = "social"
title = "X Social"
url   = "https://x.com/wcktoken"

# Last updated: 2025-08-12

[[CURRENCIES.urls]]
type  = "social"
title = "Telegram"
url   = "https://t.me/wicktoken"

[[ACCOUNTS]]
address = "rpFVEydkZrUjf4tcbLeDeVqXm5zYQGtXWm"
network = "main"
role    = "issuer"
desc    = "Official $WCK token issuer"
domain  = "wicktoken.net"

[[ACCOUNTS]]
address = "rstRegwzojXJTvhsiTnmDPbPTSKBPBZ55t"
network = "main"
role    = "treasury"
desc    = "Treasury / OTC"

[[ACCOUNTS]]
address = "rwzsLBhRkyux8rUBCZEmkuJcDK5s3LSB3K"
network = "main"
role    = "liquidity"
desc    = "DEX / pools"

[[ACCOUNTS]]
address = "rEkZ6smniCBbSuAvNdQfLRKHcgsLXiqEX1"
network = "main"
role    = "reserve"
desc    = "Principal wallet"
