[METADATA]
token = "$WCK"
name = "CONTINENTAL WICK"
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
url = "https://wicktoken.net"

[[CURRENCIES]]
code = "$WCK"
issuer = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
display_decimals = 6
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
url = "https://wicktoken.net"
logo = "ipfs://bafkreiajbbmrlqvhxajx7tihkbgnlwsolovkxxjjks4r7drs3w75oze3xy"
