[METADATA]
token = "$WCK"
disclaimer = "ipfs://bafkreibm6zcx4gcm6dgi6fkoqfzv2btbmbvb5z6ar5wrnmvyvjh654lsvi"

[[ISSUERS]]
address = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
name = "CONTINENTAL WICK"
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
url = "https://wicktoken.net"

[[CURRENCIES]]
code = "$WCK"
issuer = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
display_decimals = 6
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
url = "https://wicktoken.net"
logo = "https://ipfs.io/ipfs/bafkreiajbbmrlqvhxajx7tihkbgnlwsolovkxxjjks4r7drs3w75oze3xy"

[[TOKENS]]
issuer = "rEtKBaH1koMJtQiqdhDNgS4ZrUNsJKc5go"
currency = "$WCK"
name = "CONTINENTAL WICK"
desc = "$WCK is the native asset of the CONTINENTAL protocol. Powered by XRPL for speed, privacy, and real-world execution."
icon = "https://ipfs.io/ipfs/bafkreiajbbmrlqvhxajx7tihkbgnlwsolovkxxjjks4r7drs3w75oze3xy"
display_decimals = 6

[[TOKENS.URLS]]
url = "https://wicktoken.net"
logo = "https://ipfs.io/ipfs/bafkreiajbbmrlqvhxajx7tihkbgnlwsolovkxxjjks4r7drs3w75oze3xy"
type = "website"

[[TOKENS.URLS]]
url = "https://x.com/wick_token"
type = "social"
